name: main

on:
  push:
    branches: main
  gollum:
  workflow_dispatch:
  schedule:
    - cron: "1,2 0 * * *"
    - cron: "1,2 4 * * *"
    - cron: "1,2 10 * * *"
    
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build and publish
      env:
        USERINFO: ${{ secrets.USERINFO }}
      run: |
        python index.py
